{% set name = "fast_float" %}
{% set version = "5.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/fastfloat/fast_float/archive/v{{ version }}.tar.gz
  sha256: 2f3bc50670455534dcaedc9dcd0517b71152f319d0cec8625f21c51d23eaf4b9

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - ninja

test:
  requires:
    - cmake
    - {{ compiler('cxx') }}
    - ninja
  files:
    - test

  commands:
    - test -f ${PREFIX}/include/fast_float/fast_float.h  # [unix]
    - if not exist %PREFIX%\\Library\\include\\fast_float\\fast_float.h exit 1  # [win]
    - test -f $PREFIX/share/cmake/FastFloat/FastFloatConfig.cmake  # [unix]
    - if not exist %PREFIX%\\Library\\share\\cmake\\FastFloat\\FastFloatConfig.cmake exit 1  # [win]
    - cd test
    - cmake . -GNinja -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --config Release
    - ./program  # [unix]
    - program.exe  # [win]

about:
  home: https://github.com/fastfloat/fast_float
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: Fast and exact implementation of the C++ from_chars functions for float and double types

extra:
  recipe-maintainers:
    - apmorton
